# Generated by Django 4.0.4 on 2024-10-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateField(auto_now_add=True, help_text='Укажите дату создания', null=True, verbose_name='Дата создания'),
        ),
    ]
