# Generated by Django 5.0.6 on 2024-06-08 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_modified',
            new_name='updated_at',
        ),
    ]
